schema_version: "1.0"
mcp_name: "Liechtenstein Law MCP"
jurisdiction: "LI"

sources:
  - name: "Landesverwaltung Liechtenstein"
    authority: "Landesverwaltung Liechtenstein"
    official_portal: "https://www.gesetze.li"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "weekly"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "Government Open Data"
      url: "https://www.gesetze.li"
      summary: "Official legislative texts are public domain"
    coverage:
      scope: "Data protection, cybersecurity, e-commerce, criminal law cyber provisions"
      limitations: "AI-generated seed data; full official ingestion pending"
    languages:
      - "de"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-21"
