schema_version: "1.0"
mcp_name: "Liechtenstein Law MCP"
jurisdiction: "LI"

sources:
  - name: "Lilex - Gesetzesdatenbank des Fürstentums Liechtenstein"
    authority: "Rechtsdienst der Regierung (RDR), Liechtensteinische Landesverwaltung"
    official_portal: "https://www.gesetze.li/konso"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "unknown"
    license_or_terms:
      type: "government_terms"
      url: "https://www.gesetze.li/konso/suche"
      summary: "Die konsolidierten Texte dienen der Information; rechtlich verbindlich sind die kundgemachten Fassungen im Landesgesetzblatt."
    coverage:
      scope: "Konsolidiertes Landesrecht inklusive historischer Fassungen nach LGBl-Nummer."
      limitations: "Portal nutzt dynamische HTML-Seiten mit eingebettetem Text-iframe; Search-Endpunkte sind teilweise cookie-abhängig."
    languages:
      - "de"
